* Folium 라이브러리 설치
    * pip install folium

In [1]:
import folium

In [2]:
folium.__version__

'0.19.5'

# Map

## 기본 맵 생성
* **`folium.Map()`**
    * **`location`**
        * 지도의 중심 위도,경도 설정
        * 리스트 또는 튜플 형태로 값 전달
    * **`zoom_start`**
        * 지도 확대의 정도 설정 (최대 : 18)

In [32]:
# ----------------------------------
# 지도 중심 
#   서울시청
# ----------------------------------
loc = (37.56685, 126.9784) 

# ----------------------------------
# 서울시청을 중심으로 지도 생성
#   zoom_start
#   width
#   height
# ----------------------------------

m = folium.Map(loc
              , zoom_start=18
              , width=600
              , height=400)

# 지도에 표시
m

# Marker
* 지도의 특정 위치에 마커를 표시할 수 있다.

In [33]:
# ----------------------------------
# 지도 중심 
#   서울시청
# ----------------------------------
loc = (37.56685, 126.9784) 

# ----------------------------------
# 1. 서울시청을 중심으로 지도 생성
#   zoom_start
#   width
#   height
# ----------------------------------
m = folium.Map(loc
              , zoom_start=18
              , width=600
              , height=400)

# ----------------------------------
# 2. 서울시청에 마커 추가
#   popup='서울시청'
#   tooltip = 'Seoul City Hall'
# ----------------------------------
folium.Marker(loc
             , popup='서울시청'
             , tooltip = 'Seoul City Hall').add_to(m)

# 지도에 표시
m

## Marker 추가하기
* 다음과 같은 순서로 마커를 지도에 추가한다.
    1. 지도객체를 생성한다.
    2. 마커를 생성하여 지도 객체에 추가한다.
    <br><br>
* 마커를 생성하여 지도 객체 추가
    * **`folium.Marker(params).add_to(지도객체)`**  
        * `location` = 마커를 표시할 (위도, 경도)   
        * `popup` = 클릭했을 때 팝업창   
        * `tooltip` = 마우스 오버했을 때 보여줄 툴팁

### Marker 실습문제
1. 서울시청을 중심으로 지도 생성
2. 아래 위치에 마커 추가
    * 덕수궁 : (37.56585, 126.9751)
    * 롯데호텔 : (37.56526, 126.9809)
    * 서울도서관 : (37.56627, 126.9778)

In [34]:
# ----------------------------------
# 지도 중심 위도, 경도
#   - 서울시청
# ----------------------------------
loc = (37.56685, 126.9784) 

# ----------------------------------
# 마커를 추가할 위도, 경도
# ----------------------------------
mloc1 = (37.56582, 126.9751) # 덕수궁
mloc2 = (37.56526, 126.9809) # 롯데호텔
mloc3 = (37.56627, 126.9778) # 서울도서관

# ----------------------------------
# 1. 지도 생성
# ----------------------------------
m = folium.Map(loc
          , zoom_start=17)

# ----------------------------------
# 2. 마커를 생성하여 지도에 추가
#       tooltip
# ----------------------------------
folium.Marker(mloc1, tooltip='덕수궁').add_to(m)
folium.Marker(mloc2, tooltip='롯데호텔').add_to(m)
folium.Marker(mloc3, tooltip='서울도서관').add_to(m)

m


## circle 추가하기       
* **`folium.Circle(params).add_to(지도객체)`**      
    * `location` : 마커를 표시할 (위도, 경도)
    * `popup` : 클릭했을 때 팝업창
    * `tooltip` : 마우스 오버했을 때 보여줄 툴팁     
    * `color`: 색상   
    * `fill_color`: 채우기
    * `radius` : 반지름

In [35]:
import folium

# 서울시청 위도/경도
loc = (37.56685, 126.9784)
# ----------------------------------
# 1. 서울시청을 중심으로 지도 생성
# ----------------------------------
m = folium.Map(loc
              , zoom_start=18
              , width=600
              , height=400)

# ----------------------------------
# 2. 서울시청에 서클마커 추가
#       popup='서울시청'
#       tooltip = 'Seoul City Hall'
#       fill_color='red'
#       radius=30
# ----------------------------------
folium.Circle(loc
             , popup='서울시청'
             , tooltip = 'Seoul City Hall'
             , color='red'
             , fill_color='red'
             , radius=30).add_to(m)

# 지도에 표시
m

### Circle 실습문제
1. 서울시청을 중심으로 지도 생성
2. 아래 위치에 각각 다른 색으로 Circle 추가
    * 덕수궁 : (37.56585, 126.9751)
    * 롯데호텔 : (37.56526, 126.9809)
    * 서울도서관 : (37.56627, 126.9778)

In [36]:
import folium

# 지도 중심 위도, 경도
loc = (37.56685, 126.9784) # 서울시청

# 마커를 추가할 위도, 경도
mloc1 = (37.56585, 126.9751) # 덕수궁
mloc2 = (37.56526, 126.9809) # 롯데호텔
mloc3 = (37.56627, 126.9778) # 서울도서관

# ----------------------------------
# 1. 지도 생성
# ----------------------------------
m = folium.Map(loc
               , zoom_start=17)

# ----------------------------------
# 2. 마커를 생성하여 지도에 추가
# ----------------------------------
folium.Circle(mloc1
              , tooltip = '덕수궁'
              , color='blue'
              , fill_color='blue'
              , radius = 30).add_to(m)

folium.Circle(mloc2
              , tooltip = '롯데호텔'
              , color='red'
              , fill_color='red'
              , radius = 30).add_to(m)

folium.Circle(mloc3
              , tooltip = '서울도서관'
              , color='green'
              , fill_color='green'
              , radius = 30).add_to(m)
m

## 서울시 응급실 위치 정보

In [37]:
import pandas as pd
url = 'data/서울_응급실_위치정보.csv'
df = pd.read_csv(url, encoding='utf-8')
df = df[['병원분류명','기관명','응급실전화','병원경도','병원위도']]
df.head()

  병원분류명             기관명         응급실전화        병원경도       병원위도
0  종합병원  가톨릭대학교 여의도성모병원  02-3779-1188  126.936731  37.518272
1  종합병원   가톨릭대학교 은평성모병원  02-1811-7755  126.916150  37.633608
2    병원          강남고려병원   02-874-7227  126.956782  37.485619
3  종합병원         강남베드로병원     1544-7522  127.039587  37.485612
4    병원           강남힐병원   02-853-9100  126.911648  37.481651

In [38]:
import folium
# ----------------------------------------------
# 1. 지도 생성
#       지도 중심 : 위도평균, 경도평균
# ----------------------------------------------

loc = (df['병원위도'].mean(), df['병원경도'].mean())

m = folium.Map(loc
          , zoom_start=11)

# ----------------------------------------------
# 2. 마커 생성
# ----------------------------------------------
for i in df.index:
    gubun = df.iloc[i,0]
    name = df.iloc[i,1]
    tel = df.iloc[i,2]
    lon = df.iloc[i,3]
    lat = df.iloc[i,4]

    color_gubun = 'red' if gubun=='종합병원' else 'blue'

    folium.Marker([lat, lon]
                  , tooltip=name
                  , popup=tel
                  , icon=folium.Icon(color=color_gubun)).add_to(m)

m

# 마커 클러스터
* 다음 순서로 코드를 작성한다.
    1. 지도 생성
    2. 마커클러스터를 맵에 추가
        * **`마커클러스터객체 = MarkerCluster().add_to(지도객체)`**
    3. 마커를 마커클러스터에 추가
        * **`folium.Marker().add_to(마커클러스터객체)`**

In [39]:
from folium.plugins import MarkerCluster
import folium
# ----------------------------------------------
# 1. 지도 생성
#       지도 중심 : 위도평균, 경도평균
# ----------------------------------------------
loc = (df['병원위도'].mean(), df['병원경도'].mean())

m = folium.Map(loc
          , zoom_start=11)

# ----------------------------------------------
# 2. 마커 클러스터 생성하여 맵에 추가
# ----------------------------------------------
mc = MarkerCluster().add_to(m)

# ----------------------------------------------
# 3. 마커 생성하여 마커 클러스터에 추가
# ----------------------------------------------
for i in df.index:
    gubun = df.iloc[i,0]
    name = df.iloc[i,1]
    tel = df.iloc[i,2]
    lon = df.iloc[i,3]
    lat = df.iloc[i,4]

    color_gubun = 'red' if gubun=='종합병원' else 'blue'

    folium.Marker([lat, lon]
                  , tooltip=name
                  , popup=tel
                  , icon=folium.Icon(color=color_gubun)).add_to(mc)

m

# 지도에 경계 표시하기
* 다음과 같은 순서로 한다.
    * geojson 파일 준비 --> dict객체로 파싱
    * 지도 생성   
    * 지도에 경계 표시
        * **`folium.GeoJson(dict형태의geojson데이터)).add_to(지도객체)`**

## 제주도 읍면동 경계 표시하기

In [40]:
import folium
import json


# ----------------------------------------------
# 1. geojson 
# ----------------------------------------------
geojson = 'geojson/제주_읍면동.geojson'

with open(geojson, mode='rt', encoding='utf-8') as f:
    geo = json.loads(f.read()) # 파일 내용 파싱 (--> 딕셔너리 형태로 변환)
    f.close()

# ----------------------------------------------
# 2. 지도 생성
# ----------------------------------------------
# 제주도 위도/경도
loc = (33.4996213, 126.5311884)
m = folium.Map(loc
               , zoom_start=9)

# ----------------------------------------------
# 3. 지도에 경계 표시
# ----------------------------------------------
folium.GeoJson(geo).add_to(m)
m

## 지도에 경계 표시하기 - 실습문제

* 서울시 읍면동 geojson 데이터 준비
* 지도 생성
* 지도에  읍면동 경계 추가
* 응급실 마커 추가

In [41]:
import folium
from folium.plugins import MarkerCluster
import json

# ----------------------------------------------
# 1. geojson 
# ----------------------------------------------
with open('geojson/서울_시군구.geojson', mode='rt', encoding='utf-8') as f:
    geo = json.loads(f.read()) # 파일 내용 파싱 (--> 딕셔너리 형태로 변환)
    f.close()

# ----------------------------------c------------
# 2. 지도 생성
# ----------------------------------------------
# 서울시 위도/경도
loc = (37.56685, 126.9784)
m = folium.Map(loc
               , zoom_start=11)

# ----------------------------------------------
# 3. 지도에 경계 표시
# ----------------------------------------------
folium.GeoJson(geo).add_to(m)

# ----------------------------------------------
# 4. 마커 클러스터 추가
# ----------------------------------------------
# mc = MarkerCluster().add_to(m)

# ----------------------------------------------
# 5. 응급실 마커
# ----------------------------------------------
for i in df.index:
    gubun = df.iloc[i,0]
    name = df.iloc[i,1]
    tel = df.iloc[i,2]
    lon = df.iloc[i,3]
    lat = df.iloc[i,4]

    color_gubun = 'red' if gubun=='종합병원' else 'blue'

    folium.Marker([lat, lon]
                  , tooltip=name
                  , popup=tel
                  , icon=folium.Icon(color=color_gubun)).add_to(m)

m

# Choropleth 시각화
* geojson으로 지도에 경계를 표시하고 각 영역별 데이터 수치를 색으로 표현
* **`folium.Choropleth(params).add_to(map객체)`**

## 시군구별 인구수 choropleth 시각화
* 다음과 같은 순서로 진행
    * 지도객체 생성
    * geojson 데이터를 dict로 파싱
    * choropleth 시각화

### 시군구별 인구수 데이터 준비

In [42]:
# ----------------------------------------------
# 데이터 준비
# ----------------------------------------------

df_population = pd.read_csv('data/서울_시군구_주민등록인구.csv', encoding='utf-8').iloc[1:,:]
df_population.columns = ['구이름','계','인구수']
df_population['인구수'] = df_population['인구수'].astype(int)
df_population.head(3)

   구이름  계     인구수
1  종로구  계  139498
2   중구  계  121602
3  용산구  계  209849

### Choropleth 시각화

In [43]:
# ----------------------------------------------
# 1. geojson 데이터 준비
# ----------------------------------------------

geo_json = 'geojson/서울_시군구.geojson'
with open(geo_json, mode='r', encoding='utf-8') as f:
    geo = json.loads(f.read())

# ----------------------------------------------
# 2. 서울시청을 중심으로 지도 생성
# ----------------------------------------------
# 서울시청 위도/경도
lat = 37.56685
lon = 126.9784

m = folium.Map(location=[lat, lon], zoom_start=11)

# ----------------------------------------------
# 3. choropleth 시각화
# ----------------------------------------------
folium.Choropleth(geo_data = geo
                 , data = df_population
                 , columns = ['구이름', '인구수']
                 , key_on = 'properties.SIG_KOR_NM'
                 , legend_name = '시군구별 인구수'
                 , fill_color = 'YlOrRd'
                 , fill_opacity = 0.5     # 투명도
                 , line_opacity = 0.5     # 라인 투명도
                 ).add_to(m)


m